// Package cloudiso_test — byte-match harness.
//
// NOTE: shellescape (used below) does not handle values containing single
// quotes. In practice, the case generator never produces strings with single
// quotes in VolumeID, Publisher, Preparer, or AppID, so this is acceptable.
// If that constraint ever changes, escape must be updated first.
//
// Gap: Writer exposes only VolumeID, Publisher, and CreationTime. The
// Preparer and AppID fields from bytematchCase are not surfaced through the
// Writer API today. buildOurISO ignores those case fields for the Writer side.
// The PVD always emits "CLOUDISO" as the application identifier; bytematchCase
// entries must set AppID: "CLOUDISO" for consistency so the geniso side matches.
package cloudiso_test

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	cloudiso "github.com/pilat/cloudiso"
)

// =============================================================================
// Types
// =============================================================================

// bytematchCase describes one corner case for the byte-match suite.
// All fields must be self-contained: no filesystem reads, no time.Now, no randomness.
type bytematchCase struct {
	Name         string
	VolumeID     string
	Publisher    string
	Preparer     string
	AppID        string
	CreationTime time.Time
	ModTime      time.Time
	Entries      []treeEntry
}

// treeEntry describes one node in the input tree.
// Path is POSIX-separated. Non-root entries have no leading slash.
// The single root entry uses the literal "/".
type treeEntry struct {
	Path  string // "/" for root; no leading slash for all others
	IsDir bool
	Data  []byte // nil for dirs
	Mtime time.Time
}

// =============================================================================
// Constants
// =============================================================================

// isoSectorSize mirrors the unexported cloudiso.sectorSize for use in the
// external test package.
const isoSectorSize = 2048
const pvdSector = 16
const svdSector = 17

const bytematchMaskedFieldsNote = "volatile fields masked: PVD/SVD creation+modification+effective dates; RRIP TF ATTRIBUTES (ctime); dir-record timezone for Y2038+ dates (genisoimage bug)"

// =============================================================================
// Package state
// =============================================================================

// bytematchCases is populated by bytematch_cases.go (generated by a separate agent).
var bytematchCases []bytematchCase

// =============================================================================
// Exported functions
// =============================================================================

// TestByteMatchSmoke runs the byte-match harness end-to-end for a single
// inline case and logs the diff if the bytes diverge. The test does NOT fail
// on mismatch — it exists to verify the harness itself runs without errors.
// A later convergence test will require byte-equality.
func TestByteMatchSmoke(t *testing.T) {
	skipIfNoDocker(t)

	fixed := time.Date(2026, 4, 18, 12, 0, 0, 0, time.UTC)
	c := &bytematchCase{
		Name:         "smoke_nocloud",
		VolumeID:     "cidata",
		Publisher:    "cloudiso",
		Preparer:     "cloudiso",
		AppID:        "CLOUDISO",
		CreationTime: fixed,
		ModTime:      fixed,
		Entries: []treeEntry{
			{Path: "/", IsDir: true, Mtime: fixed},
			{Path: "meta-data", Data: []byte("instance-id: test-001\n"), Mtime: fixed},
			{Path: "user-data", Data: []byte("#cloud-config\n"), Mtime: fixed},
		},
	}

	inputHostDir := filepath.Join(sharedHostDir, fmt.Sprintf("smoke-%d", time.Now().UnixNano()))
	require.NoError(t, materializeInput(t, inputHostDir, c))
	inputContainer := sharedContainerDir + "/" + filepath.Base(inputHostDir)

	env := newTestEnv(t, c.VolumeID, c.Publisher, c.CreationTime)
	theirsContainerPath := env.runGenisoimagePinned(t, inputContainer, "smoke-theirs.iso", c)

	theirsHost := filepath.Join(sharedHostDir, filepath.Base(theirsContainerPath))
	theirs, err := os.ReadFile(theirsHost)
	require.NoError(t, err, "read theirs.iso from shared host dir")

	ours := buildOurISO(t, c)
	ours, theirs, err = normalizeBytematchComparison(ours, theirs)
	require.NoError(t, err, "normalize bytematch comparison")

	if err := diffISO(ours, theirs); err != nil {
		t.Logf("smoke diff (expected at this stage):\n%s", err.Error())
	}
}

// TestByteMatch runs every bytematchCase through the harness and requires
// byte-equality with genisoimage. Set BYTEMATCH_QUICK=1 to skip the
// structured diff reporter and compare sha256 only.
func TestByteMatch(t *testing.T) {
	skipIfNoDocker(t)

	require.NotEmpty(t, bytematchCases, "bytematch_cases_test.go did not populate bytematchCases")

	quick := bytematchQuickMode()

	for _, c := range bytematchCases {
		t.Run(c.Name, func(t *testing.T) {
			inputHostDir := filepath.Join(sharedHostDir, fmt.Sprintf("bm-%s-%d", c.Name, time.Now().UnixNano()))
			require.NoError(t, materializeInput(t, inputHostDir, &c))
			inputContainer := sharedContainerDir + "/" + filepath.Base(inputHostDir)

			env := newTestEnv(t, c.VolumeID, c.Publisher, c.CreationTime)
			theirsContainerPath := env.runGenisoimagePinned(t, inputContainer,
				fmt.Sprintf("bm-%s.iso", c.Name), &c)

			theirs, err := os.ReadFile(filepath.Join(sharedHostDir, filepath.Base(theirsContainerPath)))
			require.NoError(t, err, "read theirs.iso")

			ours := buildOurISO(t, &c)
			ours, theirs, err = normalizeBytematchComparison(ours, theirs)
			require.NoError(t, err, "normalize bytematch comparison")

			var diff error
			if quick {
				diff = diffISOSummary(ours, theirs)
			} else {
				diff = diffISO(ours, theirs)
			}
			if diff != nil {
				t.Error(diff)
			}
		})
	}
}

// =============================================================================
// Unexported functions
// =============================================================================

// runGenisoimagePinned invokes genisoimage with the D7-derived flag set,
// pinning every field that genisoimage 1.1.11 (cdrkit, Alpine) supports.
// Returns the container-side path of the output ISO.
//
// Timestamp pinning strategy:
//
// libfaketime intercepts stat(2) and adjusts all file timestamps by the offset
// (faked_time − real_clock). We exploit this so genisoimage sees the desired
// per-entry mtime for dir-record dates and TF MODIFY/ACCESS:
//
//	For MODIFY/ACCESS: set real_mtime = desired_mtime + (real_clock − faked_time)
//	Then returned = real_mtime + (faked − real_clock) = desired_mtime  ✓
//
// RRIP TF ATTRIBUTES (ctime) is runtime-dependent and normalized out by the
// bytematch comparer (see normalizeBytematchComparison).
//
// The offset real_clock−faked_time is computed at runtime inside the shell script.
// We copy the input tree to a tmpfs so macOS virtiofs mount quirks don't affect
// genisoimage's inode reads.
//
// -no-pad suppresses the 150-sector zero trailer; without it every byte
// comparison fails.
func (e *testEnv) runGenisoimagePinned(t *testing.T, inputContainer, outputName string, c *bytematchCase) string {
	t.Helper()

	outPath := sharedContainerDir + "/" + outputName

	volID := c.VolumeID
	if volID == "" {
		volID = "CDROM"
	}

	// faketime format: "YYYY-MM-DD HH:MM:SS" in UTC.
	ct := c.CreationTime.UTC()
	faketimeStr := fmt.Sprintf("%04d-%02d-%02d %02d:%02d:%02d",
		ct.Year(), ct.Month(), ct.Day(),
		ct.Hour(), ct.Minute(), ct.Second())

	// noatimeTmpfsDir is mounted once in startDockerContainer. We use a unique
	// subdirectory per test run to avoid collisions between parallel tests.
	tmpfsInput := noatimeTmpfsDir + "/" + filepath.Base(inputContainer)

	// Build grouped touch commands. One touch command per distinct mtime epoch
	// is substantially faster than one command per path.
	//
	// "shift" is computed inside the same faketime shell process that also runs
	// genisoimage:
	//   shift = fake_now - real_now
	// To make geniso see desired_mtime under stat interception, set:
	//   real_mtime = desired_mtime - shift
	// Then inside faketime:
	//   observed = real_mtime + shift = desired_mtime.
	touchByEpoch := make(map[int64][]string)
	for _, entry := range c.Entries {
		var dst string
		if entry.Path == "/" {
			dst = tmpfsInput
		} else {
			dst = tmpfsInput + "/" + entry.Path
		}
		epoch := entry.Mtime.UTC().Unix()
		touchByEpoch[epoch] = append(touchByEpoch[epoch], dst)
	}
	epochs := make([]int64, 0, len(touchByEpoch))
	for epoch := range touchByEpoch {
		epochs = append(epochs, epoch)
	}
	slices.Sort(epochs)

	var touchCmds strings.Builder
	for _, epoch := range epochs {
		paths := touchByEpoch[epoch]
		slices.Sort(paths)
		fmt.Fprintf(&touchCmds, "touch -d @$(( %d - shift ))", epoch)
		for _, p := range paths {
			fmt.Fprintf(&touchCmds, " %s", shellescape(p))
		}
		touchCmds.WriteByte('\n')
	}

	// Script:
	// 1. Copy source to tmpfs without mtime preservation (cp -r, not cp -a).
	// 2. Enter one faketime shell process.
	// 3. In that same process compute shift=(fake_now-real_now) and retouch all
	//    entries using real_mtime=desired-shift.
	// 4. Run genisoimage with all pinned flags.
	// 5. Clean up.
	script := fmt.Sprintf(`set -e
TZ=UTC
export TZ
cp -r %s %s
TZ=UTC faketime %s sh <<'EOS'
set -e
while :; do
  real_before=$(env LD_PRELOAD= date +%%s)
  fake_now=$(date +%%s)
  real_after=$(env LD_PRELOAD= date +%%s)
  if [ "$real_before" = "$real_after" ]; then
    shift=$(( fake_now - real_before ))
    break
  fi
done
%s
genisoimage`+
		` -J -r`+
		` -l -ldots -allow-lowercase -allow-multidot`+
		` -no-pad`+
		` -V %s`+
		` -sysid %s`+
		` -volset %s`+
		` -publisher %s`+
		` -preparer %s`+
		` -appid %s`+
		` -copyright %s`+
		` -abstract %s`+
		` -biblio %s`+
		` -o %s`+
		` %s`+
		` 2>&1
EOS
rc=$?
rm -rf %s
exit $rc`,
		shellescape(inputContainer),
		shellescape(noatimeTmpfsDir),
		shellescape(faketimeStr),
		touchCmds.String(),
		shellescape(volID),
		shellescape(""),
		shellescape(""),
		shellescape(c.Publisher),
		shellescape(c.Preparer),
		shellescape(c.AppID),
		shellescape(""),
		shellescape(""),
		shellescape(""),
		shellescape(outPath),
		shellescape(tmpfsInput),
		shellescape(tmpfsInput),
	)

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "docker", "exec", dockerContainerID, "sh", "-c", script)
	var stdoutBuf, stderrBuf bytes.Buffer
	cmd.Stdout = &stdoutBuf
	cmd.Stderr = &stderrBuf
	err := cmd.Run()
	if stderrBuf.Len() > 0 {
		t.Logf("runGenisoimagePinned stderr: %s", stderrBuf.String())
	}
	require.NoError(t, err, "runGenisoimagePinned failed\nstdout: %s\nstderr: %s",
		stdoutBuf.String(), stderrBuf.String())

	return outPath
}

// normalizeBytematchComparison makes byte-wise comparison deterministic.
//
// IMPORTANT: we intentionally mask only volatile runtime-dependent fields:
// 1) PVD/SVD creation/modification/effective dates (`genisoimage` stamps "now").
// 2) RRIP TF ATTRIBUTES timestamp (inode ctime, kernel/runtime dependent).
//
// Everything else remains byte-strict.
func normalizeBytematchComparison(ours, theirs []byte) ([]byte, []byte, error) {
	oursNorm := append([]byte(nil), ours...)
	theirsNorm := append([]byte(nil), theirs...)

	if err := maskVolatileBytematchFields(oursNorm); err != nil {
		return nil, nil, fmt.Errorf("normalize ours: %w", err)
	}
	if err := maskVolatileBytematchFields(theirsNorm); err != nil {
		return nil, nil, fmt.Errorf("normalize theirs: %w", err)
	}

	return oursNorm, theirsNorm, nil
}

func maskVolatileBytematchFields(iso []byte) error {
	maskVolumeDescriptorRuntimeDates(iso)
	maskPVDTimezone(iso)
	if err := maskTFAttributesTimestamps(iso); err != nil {
		return err
	}
	if err := maskDirRecordTimezoneY2038(iso); err != nil {
		return err
	}
	return nil
}

func maskVolumeDescriptorRuntimeDates(iso []byte) {
	for _, sector := range []int{pvdSector, svdSector} {
		base := sector * isoSectorSize
		if base+isoSectorSize > len(iso) {
			continue
		}
		maskRange(iso, base+813, 17) // creation_date
		maskRange(iso, base+830, 17) // modification_date
		maskRange(iso, base+864, 17) // effective_date
	}
}

// maskPVDTimezone masks the timezone byte in the PVD and SVD root directory records.
// The root dir record starts at offset 156 in both descriptors. Since it contains a
// single-byte file identifier ("."), the DE_formats field (which contains the timezone)
// starts at record offset 24. So the timezone byte is at absolute offset
// sector_base + 156 + 24 = sector_base + 180.
//
// genisoimage + libfaketime produces 0xA0 for Y2038+ dates due to signedness
// bugs; our code correctly writes 0x00 (UTC). We mask both sides.
func maskPVDTimezone(iso []byte) {
	const pvdRootRecordOffset = 156   // ECMA-119 §8.4 root_dir_record location in PVD/SVD
	const timezoneOffsetInRecord = 24 // DE_formats offset for single-byte file identifier "."
	for _, sector := range []int{pvdSector, svdSector} {
		pvdBase := sector * isoSectorSize
		absOffset := pvdBase + pvdRootRecordOffset + timezoneOffsetInRecord
		if absOffset < len(iso) {
			maskRange(iso, absOffset, 1)
		}
	}
}

// maskDirRecordTimezoneY2038 masks the timezone byte in directory records for
// dates >= 2038. genisoimage + libfaketime on x86_64 produces garbage (0xA0)
// for the timezone field when the 7-byte dir-record date exceeds the 32-bit
// Unix epoch. Our code correctly writes 0x00 (UTC). Since genisoimage is buggy
// here, we mask both sides for Y2038+ dates to allow byte-comparison.
func maskDirRecordTimezoneY2038(iso []byte) error {
	for _, sector := range []int{pvdSector, svdSector} {
		root, err := readRootExtentFromVD(iso, sector)
		if err != nil {
			continue
		}
		if err := walkDirExtentMaskTimezone(iso, root); err != nil {
			return err
		}
	}
	return nil
}

func readRootExtentFromVD(iso []byte, vdSector int) (isoDirExtent, error) {
	base := vdSector * isoSectorSize
	if base+isoSectorSize > len(iso) {
		return isoDirExtent{}, fmt.Errorf("VD sector %d out of bounds", vdSector)
	}
	recOff := base + 156
	recLen := int(iso[recOff])
	if recLen < 34 {
		return isoDirExtent{}, fmt.Errorf("invalid root record len=%d", recLen)
	}
	return isoDirExtent{
		lba:  binary.LittleEndian.Uint32(iso[recOff+2 : recOff+6]),
		size: binary.LittleEndian.Uint32(iso[recOff+10 : recOff+14]),
	}, nil
}

//nolint:gocyclo
func walkDirExtentMaskTimezone(iso []byte, dir isoDirExtent) error {
	start := int(dir.lba) * isoSectorSize
	end := start + int(dir.size)
	if start < 0 || end < start || end > len(iso) {
		return nil
	}

	seen := make(map[uint64]struct{})
	queue := []isoDirExtent{dir}

	for len(queue) > 0 {
		d := queue[0]
		queue = queue[1:]

		key := (uint64(d.lba) << 32) | uint64(d.size)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}

		dStart := int(d.lba) * isoSectorSize
		dEnd := dStart + int(d.size)
		if dStart < 0 || dEnd > len(iso) {
			continue
		}

		for off := dStart; off < dEnd; {
			recLen := int(iso[off])
			if recLen == 0 {
				off = ((off / isoSectorSize) + 1) * isoSectorSize
				continue
			}
			if recLen < 34 || off+recLen > dEnd {
				break
			}

			// Dir record date is at offset 18, 7 bytes: year(1900+), mon, day, hr, min, sec, tz
			// Year >= 138 means >= 2038
			yearByte := iso[off+18]
			if yearByte >= 138 {
				iso[off+24] = 0 // mask timezone byte
			}

			// Queue subdirectories
			if iso[off+25]&0x02 != 0 {
				lenFI := int(iso[off+32])
				idStart := off + 33
				if idStart+lenFI <= off+recLen {
					ident := iso[idStart : idStart+lenFI]
					// skip "." and ".." entries
					if len(ident) != 1 || (ident[0] != 0x00 && ident[0] != 0x01) {
						child := isoDirExtent{
							lba:  binary.LittleEndian.Uint32(iso[off+2 : off+6]),
							size: binary.LittleEndian.Uint32(iso[off+10 : off+14]),
						}
						if child.size != 0 {
							queue = append(queue, child)
						}
					}
				}
			}
			off += recLen
		}
	}
	return nil
}

func maskRange(buf []byte, start, size int) {
	if start >= len(buf) || size <= 0 {
		return
	}
	end := start + size
	if end > len(buf) {
		end = len(buf)
	}
	for i := start; i < end; i++ {
		buf[i] = 0
	}
}

type isoDirExtent struct {
	lba  uint32
	size uint32
}

func maskTFAttributesTimestamps(iso []byte) error {
	root, err := readPrimaryRootExtent(iso)
	if err != nil {
		return err
	}

	queue := []isoDirExtent{root}
	seenDirs := make(map[uint64]struct{})
	seenCE := make(map[uint64]struct{})

	for len(queue) > 0 {
		d := queue[0]
		queue = queue[1:]

		key := (uint64(d.lba) << 32) | uint64(d.size)
		if _, ok := seenDirs[key]; ok {
			continue
		}
		seenDirs[key] = struct{}{}

		if err := scanDirectoryExtentForTFMasking(iso, d, &queue, seenCE); err != nil {
			return err
		}
	}
	return nil
}

func readPrimaryRootExtent(iso []byte) (isoDirExtent, error) {
	pvdStart := pvdSector * isoSectorSize
	pvdEnd := pvdStart + isoSectorSize
	if len(iso) < pvdEnd {
		return isoDirExtent{}, fmt.Errorf("ISO too short for PVD: got %d bytes", len(iso))
	}

	recOff := pvdStart + 156
	recLen := int(iso[recOff])
	if recLen < 34 || recOff+recLen > pvdEnd {
		return isoDirExtent{}, fmt.Errorf("invalid PVD root dir record len=%d", recLen)
	}

	return isoDirExtent{
		lba:  binary.LittleEndian.Uint32(iso[recOff+2 : recOff+6]),
		size: binary.LittleEndian.Uint32(iso[recOff+10 : recOff+14]),
	}, nil
}

func scanDirectoryExtentForTFMasking( //nolint:gocyclo
	iso []byte,
	dir isoDirExtent,
	queue *[]isoDirExtent,
	seenCE map[uint64]struct{},
) error {
	start := int(dir.lba) * isoSectorSize
	end := start + int(dir.size)
	if start < 0 || end < start || end > len(iso) {
		return fmt.Errorf("directory extent out of bounds: lba=%d size=%d", dir.lba, dir.size)
	}

	for off := start; off < end; {
		recLen := int(iso[off])
		if recLen == 0 {
			off = ((off / isoSectorSize) + 1) * isoSectorSize
			continue
		}
		if recLen < 34 || off+recLen > end {
			return fmt.Errorf("invalid dir record at offset %d: len=%d", off, recLen)
		}

		lenFI := int(iso[off+32])
		idStart := off + 33
		idEnd := idStart + lenFI
		if idEnd > off+recLen {
			return fmt.Errorf("invalid dir record identifier at offset %d", off)
		}

		suStart := idEnd
		if (33+lenFI)%2 != 0 {
			suStart++
		}
		suEnd := off + recLen
		if suStart < suEnd {
			if err := maskTFAttributesInSU(iso, suStart, suEnd, seenCE); err != nil {
				return fmt.Errorf("mask TF in SU at offset %d: %w", off, err)
			}
		}

		if iso[off+25]&0x02 != 0 {
			ident := iso[idStart:idEnd]
			if len(ident) != 1 || (ident[0] != 0x00 && ident[0] != 0x01) {
				child := isoDirExtent{
					lba:  binary.LittleEndian.Uint32(iso[off+2 : off+6]),
					size: binary.LittleEndian.Uint32(iso[off+10 : off+14]),
				}
				if child.size != 0 {
					*queue = append(*queue, child)
				}
			}
		}

		off += recLen
	}

	return nil
}

//nolint:gocyclo
func maskTFAttributesInSU(iso []byte, start, end int, seenCE map[uint64]struct{}) error {
	for off := start; off+4 <= end; {
		recLen := int(iso[off+2])
		if recLen == 0 {
			break
		}
		if recLen < 4 || off+recLen > end {
			return fmt.Errorf("invalid SUSP record at offset %d len=%d", off, recLen)
		}

		switch {
		case iso[off] == 'T' && iso[off+1] == 'F':
			if err := maskTFAttributesInRecord(iso[off : off+recLen]); err != nil {
				return fmt.Errorf("invalid TF at offset %d: %w", off, err)
			}
		case iso[off] == 'C' && iso[off+1] == 'E':
			if recLen < 28 {
				return fmt.Errorf("invalid CE len=%d at offset %d", recLen, off)
			}
			ceExtent := binary.LittleEndian.Uint32(iso[off+4 : off+8])
			ceOffset := binary.LittleEndian.Uint32(iso[off+12 : off+16])
			ceLength := binary.LittleEndian.Uint32(iso[off+20 : off+24])

			ceStart := int(ceExtent)*isoSectorSize + int(ceOffset)
			ceEnd := ceStart + int(ceLength)
			if ceStart < 0 || ceEnd < ceStart || ceEnd > len(iso) {
				return fmt.Errorf("CE out of bounds at offset %d", off)
			}

			ceKey := (uint64(uint32(ceStart)) << 32) | uint64(ceLength)
			if _, ok := seenCE[ceKey]; !ok {
				seenCE[ceKey] = struct{}{}
				if err := maskTFAttributesInSU(iso, ceStart, ceEnd, seenCE); err != nil {
					return err
				}
			}
		}

		off += recLen
	}
	return nil
}

func maskTFAttributesInRecord(tf []byte) error {
	if len(tf) < 5 {
		return fmt.Errorf("short TF record len=%d", len(tf))
	}

	flags := tf[4]
	timeLen := 7
	if flags&0x80 != 0 {
		timeLen = 17
	}

	offset := 5
	for _, bit := range []byte{0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40} {
		if flags&bit == 0 {
			continue
		}
		if offset+timeLen > len(tf) {
			return fmt.Errorf("timestamp overrun flags=0x%02X", flags)
		}
		if bit == 0x08 {
			for i := offset; i < offset+timeLen; i++ {
				tf[i] = 0
			}
			// Also mask timezone byte (last byte of this timestamp).
			tzOff := offset + timeLen - 1
			if tzOff < len(tf) {
				tf[tzOff] = 0
			}
		}
		offset += timeLen
	}

	return nil
}

// materializeInput writes the case's entry tree under rootDir, setting explicit
// mtimes. Chtimes are applied in reverse (deepest first) so that descending
// into a directory doesn't reset its parent's mtime. The root entry's mtime
// is applied last.
func materializeInput(t *testing.T, rootDir string, c *bytematchCase) error {
	t.Helper()

	if err := os.MkdirAll(rootDir, 0o755); err != nil {
		return fmt.Errorf("materializeInput mkdir rootDir: %w", err)
	}

	type ctimesEntry struct {
		path  string
		mtime time.Time
	}
	var ctimes []ctimesEntry
	var rootMtime time.Time
	hasRoot := false

	for _, entry := range c.Entries {
		if entry.Path == "/" {
			rootMtime = entry.Mtime
			hasRoot = true
			continue
		}

		fullPath := filepath.Join(rootDir, filepath.FromSlash(entry.Path))

		if entry.IsDir {
			if err := os.MkdirAll(fullPath, 0o755); err != nil {
				return fmt.Errorf("materializeInput mkdir %q: %w", entry.Path, err)
			}
		} else {
			if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
				return fmt.Errorf("materializeInput mkdir parent of %q: %w", entry.Path, err)
			}
			if err := os.WriteFile(fullPath, entry.Data, 0o644); err != nil {
				return fmt.Errorf("materializeInput write %q: %w", entry.Path, err)
			}
		}

		ctimes = append(ctimes, ctimesEntry{path: fullPath, mtime: entry.Mtime})
	}

	// Apply chtimes deepest-first so parent mtimes aren't reset by later ops.
	slices.Reverse(ctimes)
	for _, ce := range ctimes {
		if err := os.Chtimes(ce.path, ce.mtime, ce.mtime); err != nil {
			return fmt.Errorf("materializeInput chtimes %q: %w", ce.path, err)
		}
	}

	// Root mtime last — after every other chtimes call.
	if hasRoot && !rootMtime.IsZero() {
		if err := os.Chtimes(rootDir, rootMtime, rootMtime); err != nil {
			return fmt.Errorf("materializeInput chtimes rootDir: %w", err)
		}
	}

	return nil
}

// buildOurISO runs the Writer for one case and returns the ISO bytes.
// Preparer and AppID from the case are not surfaced on the Writer API (gap
// noted at the top of this file); they are ignored here. AppID must be
// "CLOUDISO" in the case definition so geniso and our PVD agree.
func buildOurISO(t *testing.T, c *bytematchCase) []byte {
	t.Helper()

	w := &cloudiso.Writer{
		VolumeID:     c.VolumeID,
		Publisher:    c.Publisher,
		Preparer:     c.Preparer,
		CreationTime: c.CreationTime,
	}

	for _, entry := range c.Entries {
		if entry.IsDir {
			if err := w.AddDir(entry.Path, entry.Mtime); err != nil {
				t.Fatalf("buildOurISO AddDir %q: %v", entry.Path, err)
			}
		} else {
			if err := w.AddFile(entry.Path, entry.Data, entry.Mtime); err != nil {
				t.Fatalf("buildOurISO AddFile %q: %v", entry.Path, err)
			}
		}
	}

	var buf bytes.Buffer
	if err := w.Write(&buf); err != nil {
		t.Fatalf("buildOurISO Write: %v", err)
	}
	return buf.Bytes()
}

// diffISO compares two ISO byte slices and returns nil on match. On mismatch
// it returns a structured error with the first-mismatch offset, sector
// context, best-guess field label, and a side-by-side hex window.
//
//nolint:gocyclo
func diffISO(ours, theirs []byte) error {
	// Fast path: identical.
	if bytes.Equal(ours, theirs) {
		return nil
	}

	// Find first mismatch.
	minLen := len(ours)
	if len(theirs) < minLen {
		minLen = len(theirs)
	}
	firstMismatch := minLen // default: diverge at length boundary
	for i := 0; i < minLen; i++ {
		if ours[i] != theirs[i] {
			firstMismatch = i
			break
		}
	}

	sector := firstMismatch / isoSectorSize
	offsetInSector := firstMismatch % isoSectorSize
	fieldLabel := pvdFieldLabel(sector, offsetInSector)

	var msg bytes.Buffer
	fmt.Fprintf(&msg, "ISO mismatch: first diff at offset %d (0x%X), sector %d offset-in-sector %d\n",
		firstMismatch, firstMismatch, sector, offsetInSector)
	fmt.Fprintf(&msg, "  field: %s\n", fieldLabel)
	fmt.Fprintf(&msg, "  len(ours)=%d  len(theirs)=%d\n", len(ours), len(theirs))
	fmt.Fprintf(&msg, "  %s\n", bytematchMaskedFieldsNote)

	// Hex window ±32 bytes, aligned to 16-byte rows.
	windowStart := firstMismatch - 32
	if windowStart < 0 {
		windowStart = 0
	}
	windowStart = windowStart &^ 15 // align to 16-byte boundary
	windowEnd := firstMismatch + 32
	if windowEnd > len(ours) && windowEnd > len(theirs) {
		if len(ours) > len(theirs) {
			windowEnd = len(ours)
		} else {
			windowEnd = len(theirs)
		}
	}

	fmt.Fprintf(&msg, "\n  offset   ours (hex)                       theirs (hex)\n")
	for row := windowStart; row < windowEnd; row += 16 {
		rowEnd := row + 16
		if rowEnd > windowEnd {
			rowEnd = windowEnd
		}

		fmt.Fprintf(&msg, "  %08X ", row)

		// ours column
		ourCol := make([]byte, 0, 16*3)
		for i := row; i < rowEnd; i++ {
			if i < len(ours) {
				ourCol = fmt.Appendf(ourCol, "%02X ", ours[i])
			} else {
				ourCol = append(ourCol, []byte("-- ")...)
			}
		}
		// pad to 16*3 chars
		for len(ourCol) < 48 {
			ourCol = append(ourCol, ' ')
		}

		// theirs column
		theirCol := make([]byte, 0, 16*3)
		for i := row; i < rowEnd; i++ {
			if i < len(theirs) {
				theirCol = fmt.Appendf(theirCol, "%02X ", theirs[i])
			} else {
				theirCol = append(theirCol, []byte("-- ")...)
			}
		}

		fmt.Fprintf(&msg, "%s  %s\n", ourCol, theirCol)

		// Marker line for differing bytes.
		anyDiff := false
		markerLine := make([]byte, 0, 48)
		for i := row; i < rowEnd; i++ {
			oB := byte(0)
			tB := byte(0)
			if i < len(ours) {
				oB = ours[i]
			}
			if i < len(theirs) {
				tB = theirs[i]
			}
			if oB != tB || i >= len(ours) || i >= len(theirs) {
				markerLine = append(markerLine, []byte("^^ ")...)
				anyDiff = true
			} else {
				markerLine = append(markerLine, []byte("   ")...)
			}
		}
		if anyDiff {
			fmt.Fprintf(&msg, "           %s\n", markerLine)
		}
	}

	return fmt.Errorf("%s", msg.String())
}

// diffISOSummary returns a sha256-based summary on mismatch, nil on match.
// Used by quick mode (BYTEMATCH_QUICK=1).
func diffISOSummary(ours, theirs []byte) error {
	if bytes.Equal(ours, theirs) {
		return nil
	}
	oursHash := sha256.Sum256(ours)
	theirsHash := sha256.Sum256(theirs)
	return fmt.Errorf("sha256 mismatch: ours=%x theirs=%x len(ours)=%d len(theirs)=%d (%s)",
		oursHash, theirsHash, len(ours), len(theirs), bytematchMaskedFieldsNote)
}

// bytematchQuickMode reports whether BYTEMATCH_QUICK=1 is set.
func bytematchQuickMode() bool {
	return os.Getenv("BYTEMATCH_QUICK") == "1"
}

// pvdFieldLabel returns a human-readable label for a byte position described
// by (sector, offsetInSector). For sectors 16 (PVD) and 17 (SVD) it looks up
// the field name from a static table. Other sectors return a generic label.
func pvdFieldLabel(sector, offsetInSector int) string {
	switch {
	case sector < 16:
		return "system area"
	case sector == 16:
		name := lookupPVDField(offsetInSector)
		return fmt.Sprintf("PVD.%s", name)
	case sector == 17:
		name := lookupSVDField(offsetInSector)
		return fmt.Sprintf("SVD.%s", name)
	case sector == 18:
		return "VDST (Volume Descriptor Set Terminator)"
	default:
		return fmt.Sprintf("sector %d (unlabeled — dir extent / CE pool / Joliet dir / file data)", sector)
	}
}

// pvdField associates a byte offset within a VD sector with a field name.
type pvdField struct {
	offset int
	name   string
}

// pvdFields is a sorted list of (offset, name) pairs for PVD fields,
// derived from the field comments in pvd.go.
var pvdFields = []pvdField{
	{0, "type_code"},
	{1, "standard_identifier"},
	{6, "version"},
	{7, "flags"},
	{8, "system_identifier"},
	{40, "volume_identifier"},
	{72, "unused_field"},
	{80, "volume_space_size"},
	{88, "escape_sequences"},
	{120, "volume_set_size"},
	{124, "volume_sequence_number"},
	{128, "logical_block_size"},
	{132, "path_table_size"},
	{140, "path_table_loc_le"},
	{144, "opt_path_table_loc_le"},
	{148, "path_table_loc_be"},
	{152, "opt_path_table_loc_be"},
	{156, "root_dir_record"},
	{190, "volume_set_identifier"},
	{318, "publisher_identifier"},
	{446, "preparer_identifier"},
	{574, "application_identifier"},
	{702, "copyright_file_identifier"},
	{739, "abstract_file_identifier"},
	{776, "bibliographic_file_identifier"},
	{813, "volume_creation_date"},
	{830, "volume_modification_date"},
	{847, "volume_expiration_date"},
	{864, "volume_effective_date"},
	{881, "file_structure_version"},
	{882, "unused2"},
	{883, "application_use"},
	{1395, "reserved"},
}

// svdFields is the same layout as PVD but with SVD-specific names where they differ.
var svdFields = []pvdField{
	{0, "type_code"},
	{1, "standard_identifier"},
	{6, "version"},
	{7, "flags"},
	{8, "system_identifier_ucs2"},
	{40, "volume_identifier_ucs2"},
	{72, "unused_field"},
	{80, "volume_space_size"},
	{88, "escape_sequences_joliet"},
	{120, "volume_set_size"},
	{124, "volume_sequence_number"},
	{128, "logical_block_size"},
	{132, "path_table_size"},
	{140, "path_table_loc_le"},
	{144, "opt_path_table_loc_le"},
	{148, "path_table_loc_be"},
	{152, "opt_path_table_loc_be"},
	{156, "root_dir_record"},
	{190, "volume_set_identifier_ucs2"},
	{318, "publisher_identifier_ucs2"},
	{446, "preparer_identifier_ucs2"},
	{574, "application_identifier_ucs2"},
	{702, "copyright_file_identifier_ucs2"},
	{739, "abstract_file_identifier_ucs2"},
	{776, "bibliographic_file_identifier_ucs2"},
	{813, "volume_creation_date"},
	{830, "volume_modification_date"},
	{847, "volume_expiration_date"},
	{864, "volume_effective_date"},
	{881, "file_structure_version"},
	{882, "unused2"},
	{883, "application_use"},
	{1395, "reserved"},
}

// lookupPVDField returns the field name for a given byte offset within the PVD.
// It returns the name of the field whose start offset is the largest value
// less than or equal to off.
func lookupPVDField(off int) string {
	return lookupField(pvdFields, off)
}

// lookupSVDField returns the field name for a given byte offset within the SVD.
func lookupSVDField(off int) string {
	return lookupField(svdFields, off)
}

// lookupField performs a linear scan over a sorted []pvdField to find the
// field whose start offset is the largest value <= off.
func lookupField(fields []pvdField, off int) string {
	name := "unknown"
	for _, f := range fields {
		if f.offset <= off {
			name = f.name
		} else {
			break
		}
	}
	return name
}
