package cloudiso

import (
	"fmt"
	"slices"
	"strings"
	"unicode/utf16"
)

// iso9660NameLen is genisoimage's iso9660_namelen (LEN_ISONAME): the maximum
// number of characters in the primary-tree file name part (before version
// suffix). With -l (full_iso9660_filenames) it stays at 31.
const iso9660NameLen = 31

// validate checks a single path component under permissive Level-2-like rules
// (equivalent to genisoimage -l -ldots -allow-lowercase -allow-multidot).
// Allowed characters: [A-Za-z0-9._-], length 1–31. The strings "." and ".."
// are always rejected as reserved names.
//
// The upper bound is iso9660_namelen = 31 (LEN_ISONAME with -l). Names longer
// than 30 chars that lack a dot get their ISO FI truncated in fileID() to fit
// within iso9660_namelen bytes (the NM record always carries the full name).
//
// Joliet constraints are also checked here: max 64 UCS-2 code units per
// component (Joliet spec §3), and no code points above U+FFFF (surrogate pairs
// would split into two UTF-16 units, violating the UCS-2 contract).
func validate(name string) error {
	if name == "" {
		return fmt.Errorf("empty name component")
	}
	if name == "." || name == ".." {
		return fmt.Errorf("reserved name %q", name)
	}
	if len(name) > iso9660NameLen {
		return fmt.Errorf("name %q exceeds %d characters", name, iso9660NameLen)
	}
	for _, c := range name {
		if !isAllowedChar(c) {
			return fmt.Errorf("name %q contains invalid character %q", name, c)
		}
	}

	// Joliet: max 64 UCS-2 code units per component (Joliet spec §3).
	// All current allowed chars are ASCII (≤U+007F), so utf16.Encode returns
	// exactly one unit per rune. We still verify that no surrogate pair sneaks
	// through a future charset extension.
	units := utf16.Encode([]rune(name))
	if len(units) > 64 {
		return fmt.Errorf("name %q exceeds 64 UCS-2 code units for Joliet", name)
	}
	for _, u := range units {
		// Surrogate range U+D800–U+DFFF cannot be represented in UCS-2.
		if u >= 0xD800 && u <= 0xDFFF {
			return fmt.Errorf("name %q contains a surrogate code point invalid for Joliet UCS-2", name)
		}
	}
	return nil
}

// fileID returns the on-disk primary-tree file identifier per ECMA-119 §9.1.6
// as generated by genisoimage 1.1.11 with -l -r -allow-lowercase -allow-multidot:
//
//   - Characters '#', '-', '~' are translated to '_' (iso_translate=1 default).
//   - If the translated name contains no '.', a separator dot is appended before
//     the version suffix.
//   - When the name has no dot and its length >= iso9660NameLen-1 (=30), genisoimage
//     NUL-terminates at position iso9660NameLen-1 (=30), keeping 30 chars, then
//     appends ".;1" — producing LEN_FI=33. (name.c: pnt[iso9660_namelen-1] = '\0')
//   - The version suffix ";1" is always appended.
//
// The NM (Rock Ridge) record carries the original unmodified name.
func fileID(name string) string {
	translated := translateISO9660(name)
	if !strings.Contains(translated, ".") {
		// Must add a separator dot. If the name fills the allowed space
		// (>= iso9660NameLen-1 = 30 chars), drop the last char before adding
		// ".;1" — matching genisoimage name.c which sets pnt[strlen(pnt)-1]='\0'
		// (effectively removing one char) when strlen >= iso9660_namelen-1.
		if len(translated) >= iso9660NameLen-1 {
			translated = translated[:len(translated)-1]
		}
		return translated + ".;1"
	}
	return translated + ";1"
}

// translateISO9660 applies genisoimage's iso_translate=1 character mapping:
// '#', '-', and '~' are replaced by '_'. All other characters are preserved.
func translateISO9660(name string) string {
	if !strings.ContainsAny(name, "#-~") {
		return name
	}
	var b strings.Builder
	b.Grow(len(name))
	for _, c := range name {
		switch c {
		case '#', '-', '~':
			b.WriteByte('_')
		default:
			b.WriteRune(c)
		}
	}
	return b.String()
}

// isAllowedChar reports whether c is permitted in a permissive primary-tree
// name component: A-Z, a-z, 0-9, underscore, hyphen, dot.
func isAllowedChar(c rune) bool {
	return (c >= 'A' && c <= 'Z') ||
		(c >= 'a' && c <= 'z') ||
		(c >= '0' && c <= '9') ||
		c == '_' || c == '-' || c == '.'
}

// splitPath normalises a path string into components, stripping a leading
// slash if present. It returns an error for paths containing empty components.
func splitPath(p string) ([]string, error) {
	p = strings.TrimPrefix(p, "/")
	if p == "" {
		return nil, fmt.Errorf("empty path")
	}
	parts := strings.Split(p, "/")
	if slices.Contains(parts, "") {
		return nil, fmt.Errorf("path %q contains empty component (double slash)", p)
	}
	return parts, nil
}
